apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: kuard
  namespace: kuard
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
